// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9FXUs9pi8RkbNx5smRb3ozstlyv5bVIE',
    appId: '1:386530691152:android:3247e550abac0fe3392955',
    messagingSenderId: '386530691152',
    projectId: 'wetravel-bebad',
    databaseURL: 'https://wetravel-bebad-default-rtdb.firebaseio.com',
    storageBucket: 'wetravel-bebad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvcVJB3KxiSqQbV-JD8FnlemHB_h0kjoI',
    appId: '1:386530691152:ios:ab211b9047bdddf1392955',
    messagingSenderId: '386530691152',
    projectId: 'wetravel-bebad',
    databaseURL: 'https://wetravel-bebad-default-rtdb.firebaseio.com',
    storageBucket: 'wetravel-bebad.firebasestorage.app',
    iosClientId: '386530691152-lipcg3e988u34ii6uji67oofmn5qj2vs.apps.googleusercontent.com',
    iosBundleId: 'com.tteonabojo.weetravel',
  );

}